version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: task_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: root
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: task_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres

volumes:
  postgres_data: